FROM python:3.8.5-buster

RUN mkdir /code

WORKDIR /code

ADD requirements.txt /code/

RUN pip install -r requirements.txt

COPY scripts/start.*.sh /

WORKDIR /

RUN chmod +x start.dev.sh

WORKDIR /code

ADD . /code/